name: Run tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
#  php-tests:
#    runs-on: ${{ matrix.os }}
#
#    strategy:
#      matrix:
##        php: [7.4, 7.3, 7.2, 7.1]
##        laravel: [6.*, 5.8.*, 5.7.*, 5.6.*, 5.5.*]
#        php: [7.4]
#        laravel: [6.*]
#        dependency-version: [prefer-stable]
#        os: [ubuntu-latest]
#        redis: [5-alpine]
#        exclude:
#          - laravel: 6.*
#            php: 7.1
#          - laravel: 5.7.*
#            php: 7.4
#          - laravel: 5.6.*
#            php: 7.4
#          - laravel: 5.5.*
#            php: 7.4
#
#    name: P${{ matrix.php }} - L${{ matrix.laravel }} - Insecure
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v1
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php }}
#          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath
#          coverage: none
#
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        with:
#          path: ~/.composer/cache/files
#          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
#
#      - name: Run redis without password
#        run: |
#          docker run -p 6379:6379 --name redis -d redis:${{ matrix.redis }}
#
#      - name: Install dependencies
#        run: |
#          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
#          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
#
#      - name: Execute tests
#        # we need to split the tests into two classes one for secure and one for insecure redis
#        run: vendor/bin/phpunit --exclude-group=redis-auth
#        env:
#          REDIS_HOST: redis

  redis-with-password:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #        php: [7.4, 7.3, 7.2, 7.1]
        #        laravel: [6.*, 5.8.*, 5.7.*, 5.6.*, 5.5.*]
        php: [7.4]
        laravel: [6.*]
        dependency-version: [prefer-stable]
        os: [ubuntu-latest]
        redis: [5-alpine]
        exclude:
          - laravel: 6.*
            php: 7.1
          - laravel: 5.7.*
            php: 7.4
          - laravel: 5.6.*
            php: 7.4
          - laravel: 5.5.*
            php: 7.4

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - Secure

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Run redis with password
        uses: getong/redis-action@v1
        with:
          redis version: ${{ matrix.redis }}
          host port: 6380
          redis password: 'secret'

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        # we need to split the tests into two classes one for secure and one for insecure redis
        run: vendor/bin/phpunit
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6380
